# Generated by Django 4.2.30 on 2026-06-15 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_difference', models.DecimalField(decimal_places=2, help_text='正数为补交，负数为退还', max_digits=10, verbose_name='差价')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='改签手续费')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PAID', '已支付差价'), ('COMPLETED', '已完成')], default='PENDING', max_length=20, verbose_name='改签状态')),
                ('new_cabin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='flights.cabinclass', verbose_name='新舱位')),
                ('new_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='flights.flight', verbose_name='新航班')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='orders.order', verbose_name='原订单')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='orders.passenger', verbose_name='原乘机人')),
            ],
            options={
                'verbose_name': '改签申请',
                'verbose_name_plural': '改签申请',
                'db_table': 'reschedules_reschedule_request',
            },
        ),
    ]
