# Generated by Django 4.2.30 on 2026-06-15 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, verbose_name='服务名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='服务单价')),
            ],
            options={
                'verbose_name': '附加服务',
                'verbose_name_plural': '附加服务',
                'db_table': 'orders_addon_service',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付/出票中'), ('TICKETED', '已出票'), ('REFUNDING', '退票中'), ('REFUNDED', '已退票'), ('RESCHEDULED', '已改签'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('pay_expire_at', models.DateTimeField(db_index=True, verbose_name='支付截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cabin_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='flights.cabinclass', verbose_name='舱位')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='flights.flight', verbose_name='航班')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_no', models.CharField(max_length=30, unique=True, verbose_name='支付流水号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际支付金额')),
                ('method', models.CharField(default='MOCK', max_length=30, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('PENDING', '待支付'), ('SUCCESS', '支付成功'), ('FAILED', '支付失败')], default='PENDING', max_length=20, verbose_name='支付状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付成功时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '支付流水',
                'verbose_name_plural': '支付流水',
                'db_table': 'orders_payment',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_type', models.CharField(choices=[('ID_CARD', '身份证'), ('PASSPORT', '护照')], max_length=20, verbose_name='证件类型')),
                ('id_number', models.CharField(max_length=50, verbose_name='证件号')),
                ('passenger_type', models.CharField(choices=[('ADULT', '成人'), ('CHILD', '儿童'), ('INFANT', '婴儿')], max_length=10, verbose_name='乘机人类型')),
                ('ticket_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='电子票号')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('REFUNDING', '退票中'), ('REFUNDED', '已退票'), ('RESCHEDULED', '已改签')], default='NORMAL', max_length=20, verbose_name='票状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '订单乘机人',
                'verbose_name_plural': '订单乘机人',
                'db_table': 'orders_passenger',
            },
        ),
    ]
