# Generated by Django 4.2.30 on 2026-06-17 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='cabin_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_passengers', to='flights.cabinclass', verbose_name='关联舱位'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_passengers', to='flights.flight', verbose_name='关联航班'),
        ),
    ]
