# Generated by Django 4.2.30 on 2026-06-15 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预计退款金额')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='手续费')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝')], default='PENDING', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.order', verbose_name='关联订单')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.passenger', verbose_name='关联乘机人')),
            ],
            options={
                'verbose_name': '退票申请',
                'verbose_name_plural': '退票申请',
                'db_table': 'refunds_refund_request',
            },
        ),
    ]
