# Generated by Django 4.2.30 on 2026-06-15 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='机场IATA代码')),
                ('name', models.CharField(max_length=100, verbose_name='机场名称')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '机场',
                'verbose_name_plural': '机场',
                'db_table': 'flights_airport',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=20, verbose_name='航班号')),
                ('airline', models.CharField(max_length=50, verbose_name='航空公司')),
                ('departure_time', models.DateTimeField(db_index=True, verbose_name='起飞时间')),
                ('arrival_time', models.DateTimeField(verbose_name='降落时间')),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='机型')),
                ('is_direct', models.BooleanField(default=True, verbose_name='是否直飞')),
                ('stop_info', models.JSONField(blank=True, null=True, verbose_name='经停信息')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='flights.airport', verbose_name='到达机场')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='flights.airport', verbose_name='出发机场')),
            ],
            options={
                'verbose_name': '航班',
                'verbose_name_plural': '航班',
                'db_table': 'flights_flight',
            },
        ),
        migrations.CreateModel(
            name='CabinClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_type', models.CharField(choices=[('ECONOMY', '经济舱'), ('BUSINESS', '商务舱'), ('FIRST', '头等舱')], max_length=20, verbose_name='舱位类型')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础票价')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='税费')),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='燃油附加费')),
                ('total_seats', models.IntegerField(verbose_name='总座位数')),
                ('available_seats', models.IntegerField(verbose_name='可用座位数')),
                ('baggage_allowance', models.CharField(blank=True, max_length=100, null=True, verbose_name='免费行李额')),
                ('refund_rules', models.JSONField(default=list, verbose_name='退票手续费阶梯')),
                ('reschedule_rules', models.JSONField(default=list, verbose_name='改签手续费规则')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_classes', to='flights.flight', verbose_name='关联航班')),
            ],
            options={
                'verbose_name': '舱位与库存',
                'verbose_name_plural': '舱位与库存',
                'db_table': 'flights_cabin_class',
            },
        ),
    ]
