# Generated by Django 4.2.30 on 2026-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_fail_count',
            field=models.IntegerField(default=0, verbose_name='连续登录失败次数'),
        ),
    ]
