# Generated by Django 4.2.30 on 2026-06-17 02:41

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_login_fail_count'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='frequentpassenger',
            unique_together={('user', 'id_number')},
        ),
    ]
